language: scala

env:
  - GCLOUD_SERVICE_KEY_LOCATION="${HOME}/gcloud-service-key.json"

scala:
  - 2.11.8

jdk:
  - oraclejdk8

before_script:
  - echo ${GCLOUD_SERVICE_KEY} | base64 --decode > ${GCLOUD_SERVICE_KEY_LOCATION}

script:
  - sbt test
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then sbt it:test; fi'
